# Generated by Django 4.2.2 on 2023-07-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('u', 'Unisex')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
