# Generated by Django 4.2.2 on 2023-07-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_stuff_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='sizes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='colors',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
